<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Clicking_On_Hamburger_Icon</name>
   <tag></tag>
   <elementGuidId>750cf559-1743-479f-a333-17c2ddb16582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/ert-app-root/ert-dashboard[@class='ng-star-inserted']/mat-sidenav-container[@class='mat-drawer-container mat-sidenav-container']/mat-sidenav[@class='app-container__side-nav mat-drawer mat-sidenav ng-tns-c13-2 ng-trigger ng-trigger-transform mat-drawer-side mat-drawer-opened ng-star-inserted']/div[@class='mat-drawer-inner-container']/ert-sidebar[@class='es-sidebar']/div[@class='sidebar sidebar__content']/mat-nav-list[@class='mat-nav-list mat-list-base']/a[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-icon mat-icon notranslate mat-icon-no-color</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>svgicon</name>
      <type>Main</type>
      <value>ERT-Menu</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-svg-icon</name>
      <type>Main</type>
      <value>ERT-Menu</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/ert-app-root[1]/ert-dashboard[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container&quot;]/mat-sidenav[@class=&quot;app-container__side-nav mat-drawer mat-sidenav ng-tns-c13-2 ng-trigger ng-trigger-transform mat-drawer-side mat-drawer-opened ng-star-inserted&quot;]/div[@class=&quot;mat-drawer-inner-container&quot;]/ert-sidebar[@class=&quot;es-sidebar&quot;]/div[@class=&quot;sidebar sidebar__content&quot;]/mat-nav-list[@class=&quot;mat-nav-list mat-list-base&quot;]/a[@class=&quot;mat-list-item ng-star-inserted&quot;]/div[@class=&quot;mat-list-item-content&quot;]/mat-icon[@class=&quot;menu-icon mat-icon notranslate mat-icon-no-color&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portfolio'])[1]/preceding::mat-icon[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-icon</value>
   </webElementXpaths>
</WebElementEntity>
