<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MouseHove_On_Quality_TornadoChat</name>
   <tag></tag>
   <elementGuidId>8a339150-908e-4030-8b8c-825a8a8c2096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>rect.bar--quality:nth-child(20)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
