<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ScattePlot_ToolTip</name>
   <tag></tag>
   <elementGuidId>251168d0-e98f-48f6-b464-bf81e4abe851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div#scatter_plot_tooltip.scatter_plot_tooltip</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
