<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Studies_By_Score_Dot_Circle</name>
   <tag></tag>
   <elementGuidId>af93b7ff-d781-4338-8d36-449737a8390a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>circle.dot</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
