<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TornadoSpanStudystyle</name>
   <tag></tag>
   <elementGuidId>21c83425-48e9-4e72-b0be-5e6caa878ddf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div#tornado_tooltip.tornado_tooltip</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
