<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MouseOver_On_ScattePlot_7</name>
   <tag></tag>
   <elementGuidId>a5523c7f-fee5-47c3-a0d4-74cd1235e1b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>circle.dot:nth-child(7)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
